### ISSUE TITLE
Add variable for sprite file for the sprite mixin

### ISSUE THREAD

**Issue by betovarg** [ManatiCR/generator-manati-theme#7]
Currently we have the sprite's filename wired on our partial.

**Comment by fedfigca** [comment]
~~This already existed, it has a default to `"../images/global-sprite"`, but can be any name.~~

The mixin requires the basename only, and must exist as png and svg.
Better documentation in the _mixins.scss file will be added:

```
// The mixin requires the image as basename only, and must exist as png and svg.
//
// usage example:
// @include sprite(red, $x: center, $y: -589px, $image: "../images/sprite");
```

**Comment by fedfigca** [comment]
Reopening to create a default in _variables.scss
